version: '3.9'
services:
  belcorp:
    image: belcorp-dev
    #image: /belcorp:dev
    container_name: belcorp-dev
    build:
      context: .
      dockerfile: Dockerfile
    networks:
     - belcorp_network
    restart: always
    ports:
      - 3010:3000
    command: yarn start

networks:
  belcorp_network:
    name: belcorp_network

startupProbe:
  httpGet:
    path: /api/healthcheck
    port: 3000
    httpHeaders:
    - name: X-Kubernetes-Probe
      value: Startup
  timeoutSeconds: 300
  periodSeconds: 30
  failureThreshold: 10
