'use client';

import { Avatar, Card } from '@mui/material';
//Internal app
import { CardDetailsProps } from '@/interfaces';

/**
 * Card used to display the result generated by third parties
 *
 * @param children - Child elements.
 * @param avatarImage - Confirm and receive the image link.
 * @param avatarText - Receive a text when you do not receive the image.
 */
export default function CardDetails(props: CardDetailsProps): JSX.Element {
  const { children, avatarImage, avatarText } = props;

  return (
    <Card
      sx={{
        borderRadius: 'shape.borderRadius',
        display: 'flex',
        justifyContent: 'space-between',
        pt: 4,
        px: 3 / 2,
        pb: 3 / 2,
        mb: 3 / 2,
      }}
    >
      <Avatar sx={{ bgcolor: 'white', position: 'absolute', top: '5px', left: '140px' }} variant="circular">
        {avatarImage ? (
          <picture>
            <img src={avatarImage.src.src} alt="Proveedor" />
          </picture>
        ) : (
          avatarText
        )}
      </Avatar>

      {children}
    </Card>
  );
}
