'use client';

import { useRef } from 'react';
import { isBrowser, isMobile, isTablet } from 'react-device-detect';
import { Box, Button, Divider, IconButton, Typography } from '@mui/material';
import { CopyToClipboard } from 'react-copy-to-clipboard';
//Internal app
import { CopyIcons } from '%/Icons';
import Qr from '%/images/arts/QR.png';
import CardReport from './CardReport';
import { fuchsiaBlue } from '@/theme/theme-default';
import { CardPagoEfectivoProps } from '@/interfaces';
import PagoEfectivo from '%/images/suppliers/pagoEfectivo.png';
import { handleDownload, handleShare } from '@/utils/toolHelper';

/**
 * Card used to display the information generated by Pago Efectivo
 *
 * @param cip - CIP code
 * @param children - Add elements from the parent
 * @param label - Label of buttons
 * @param download - handling for file download
 * @param share - handling for image shared
 */
export default function CardPagoEfectivo({ cip, children, label, download, share }: CardPagoEfectivoProps) {
  const codeQrRef = useRef<any>(null);
  const ticketRef = useRef<any>(null);

  const ImagePagoEfectivo = {
    src: PagoEfectivo,
    alt: 'Logo Pago Efectivo',
  };
  const shareData: any = {
    files: [],
    text: `¡Hola! 👋 en el siguiente link tendras los detalles para realizar la transferencia:\n\nPaga por Yape, Plin u otras billeteras escaneando el código QR que figura arriba.\n\nPaga en agentes o banca en línea por PagoEfectivo en soles con este Código CIP: 8462 1935 7079\n\n ¿Cómo pagar?\nhttps://www.pagoefectivo.la/pe/como-pagar`,
  };

  const handleShareClick = () => {
    if (isBrowser) {
      handleShare(ticketRef.current, shareData, fuchsiaBlue[800]);
    }

    if (isMobile || isTablet) {
      handleShare(codeQrRef.current, shareData, 'white');
    }
  };

  const handleDownloadClick = () => {
    handleDownload(codeQrRef.current, 'recarga.png', fuchsiaBlue[800]);
  };

  return (
    <>
      <Box ref={ticketRef} sx={{ padding: '24px 4px 4px 4px', position: 'relative' }}>
        <CardReport avatarImage={ImagePagoEfectivo}>
          <Box
            sx={{
              display: 'flex',
              flexDirection: 'column',
              textAlign: 'center',
              alignItems: 'center',
              width: 140,
            }}
          >
            <Typography fontWeight={700} mb={3}>
              Pago en agentes ó banca en línea
            </Typography>
            <Typography variant="caption" mb={2}>
              Empresa: PagoEfectivo PagoEfectivo Soles
            </Typography>
            <Typography variant="caption" fontWeight={700}>
              Código CIP:
            </Typography>
            <Typography variant="subtitle1" sx={{ display: 'flex', color: 'primary.main', alignItems: 'center' }}>
              {cip}
              <CopyToClipboard text={cip}>
                <IconButton aria-label="delete" size="small" sx={{ p: 0, ml: 1 }}>
                  <CopyIcons sx={{ color: 'primary.main' }} />
                </IconButton>
              </CopyToClipboard>
            </Typography>
          </Box>
          <Divider orientation="vertical" variant="primary" flexItem sx={{ mx: 1 }} />
          <Box
            sx={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              width: 140,
              textAlign: 'center',
            }}
          >
            <Typography fontWeight={700} mb={3}>
              Yape, Plin u otras billeteras:
            </Typography>
            <picture ref={codeQrRef}>
              <img src={Qr.src} alt="Qr Code" />
            </picture>
          </Box>
        </CardReport>
      </Box>
      {children}

      {download && (
        <Button variant="secondary" onClick={handleDownloadClick} sx={{ mb: 4 }}>
          {label}
        </Button>
      )}

      {share && (
        <Button variant="secondary" onClick={handleShareClick} sx={{ mb: 4 }}>
          {label}
        </Button>
      )}
    </>
  );
}
